### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by jl4282** [jl4282/wordpressstyle#1]
- [ ] Fix height on Astor place photo -> dynamically get background height
- [ ] Fix picture sizes for other photos -> depending on screen size use background to get larger or smaller photos
- [ ] Check other browsers
- [ ] Check throttling images
- [ ] Check various devices
